### ISSUE TITLE
Error on npm run dev

### ISSUE THREAD

**Issue by dfosco** [zehfernandes/boldo#2]
Tried to run with [this figma file](https://www.figma.com/file/gDkwB2y6qxodewUwKItg5s/RENOVATIONS), but got the error below.

Does the file has to follow specific parameters for it to work? Should I have used the prototype link?

```
[0] (node:20403) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `r` of 'undefined' or 'null'.
[0]     at parseFill (/Users/dfosco/workspace/_personal/boldo/boldo/scripts/parse-figma.js:114:38)
[0]     at parseNode (/Users/dfosco/workspace/_personal/boldo/boldo/scripts/parse-figma.js:99:22)
[0]     at walker (/Users/dfosco/workspace/_personal/boldo/boldo/scripts/parse-figma.js:50:27)
[0]     at walker (/Users/dfosco/workspace/_personal/boldo/boldo/scripts/parse-figma.js:72:7)
[0]     at parseFigma (/Users/dfosco/workspace/_personal/boldo/boldo/scripts/parse-figma.js:14:3)
[0]     at client.file.then (/Users/dfosco/workspace/_personal/boldo/boldo/scripts/watch-figma.js:38:7)
[0]     at processTicksAndRejections (internal/process/task_queues.js:86:5)
[0] (node:20403) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 84)
```

**Comment by Feruza12** [comment]
for it is showing the same error

**Comment by Feruza12** [comment]
> Tried to run with [this figma file](https://www.figma.com/file/gDkwB2y6qxodewUwKItg5s/RENOVATIONS), but got the error below.
> 
> Does the file has to follow specific parameters for it to work? Should I have used the prototype link?
> 
> ```
> [0] (node:20403) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `r` of 'undefined' or 'null'.
> [0]     at parseFill (/Users/dfosco/workspace/_personal/boldo/boldo/scripts/parse-figma.js:114:38)
> [0]     at parseNode (/Users/dfosco/workspace/_personal/boldo/boldo/scripts/parse-figma.js:99:22)
> [0]     at walker (/Users/dfosco/workspace/_personal/boldo/boldo/scripts/parse-figma.js:50:27)
> [0]     at walker (/Users/dfosco/workspace/_personal/boldo/boldo/scripts/parse-figma.js:72:7)
> [0]     at parseFigma (/Users/dfosco/workspace/_personal/boldo/boldo/scripts/parse-figma.js:14:3)
> [0]     at client.file.then (/Users/dfosco/workspace/_personal/boldo/boldo/scripts/watch-figma.js:38:7)
> [0]     at processTicksAndRejections (internal/process/task_queues.js:86:5)
> [0] (node:20403) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 84)
> ```

https://www.figma.com/file/Yfqqd1bjeTJf2iHbg0SQAo/Untitled?node-id=2%3A8  
**your template should look like in that format**

**Comment by nerypy** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @tarek-eg, @Aiden-FE, @Monte9, @twilightrus, @zaherg, @yrong, @22388o
